version: '3.8'

services:
  nginx:
    image: nginx:1.19.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./api/src:/app
      - ./nginx/conf:/etc/nginx/templates
      - dist:/web/dist
    depends_on:
      - php7
      - website
    networks:
      - api
      - web

  php7:
    build:
      context: ./php
      args:
        - WITH_XDEBUG=${WITH_XDEBUG}
        - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
        - REMOTE_HOST=${REMOTE_HOST}
        - REMOTE_POST=${REMOTE_POST}
    ports:
      - "9000:9000"
    working_dir: /app
    volumes:
      - ./api/src:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - api

  composer:
    image: library/composer:2
    volumes:
      - ./api/src:/app
    networks:
      - api

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - api

  website:
    build:
      context: ./website
      args:
        PORT: ${SERVE_PORT}
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ./website/src:/web
      - node_modules:/web/node_modules
      - dist:/web/dist
    ports:
      - "8080:${SERVE_PORT}"
    env_file:
      - .env
    networks:
      - web

volumes:
  database_mysql:
  node_modules:
  dist:

networks:
  api:
  web: