version: '3.8'

services:
  nginx:
    image: nginx:1.19.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./api:/app
#     - ./nginx:/etc/nginx/templates
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api

  php7:
    build:
      context: ./php
    ports:
      - "9000:9000"
    working_dir: /app
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - api

  composer:
    image: library/composer:2
    volumes:
      - ./api:/app
    networks:
      - api

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - database_mysql
    networks:
      - api

volumes:
  database_mysql:

networks:
  api: