version: '3.8'

services:
  nginx:
    image: nginx:1.19.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./api:/app
#     - ./nginx:/etc/nginx/templates
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api

  php7:
    image: php:7.4-fpm-alpine
    ports:
      - "9000:9000"
    working_dir: /app
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./api:/app
    networks:
      - api
    command: php-fpm

  composer:
    image: library/composer:2
    volumes:
      - ./api:/app
    networks:
      - api

networks:
  api: